### ISSUE TITLE
petrel_client

### ISSUE THREAD

**Issue by KimWu1994** [OpenLAMM/LAMM#75]
I run scripts `sh tools/LAMM/train_lamm2d.sh lamm_2d`.

An error report as follows:

```
Traceback (most recent call last):
  File "/ssd/wjl/LAMM/src/train.py", line 14, in <module>
    from model import load_model
  File "/ssd/wjl/LAMM/src/model/__init__.py", line 3, in <module>
    from .LAMM import LAMMPEFTModel
  File "/ssd/wjl/LAMM/src/model/LAMM/__init__.py", line 1, in <module>
    from .openlamm import LAMMPEFTModel
  File "/ssd/wjl/LAMM/src/model/LAMM/openlamm.py", line 3, in <module>
    from petrel_client.client import Client
ModuleNotFoundError: No module named 'petrel_client'
Traceback (most recent call last):
  File "/ssd/wjl/LAMM/src/train.py", line 14, in <module>
    from model import load_model
  File "/ssd/wjl/LAMM/src/model/__init__.py", line 3, in <module>
    from .LAMM import LAMMPEFTModel
  File "/ssd/wjl/LAMM/src/model/LAMM/__init__.py", line 1, in <module>
    from .openlamm import LAMMPEFTModel
  File "/ssd/wjl/LAMM/src/model/LAMM/openlamm.py", line 3, in <module>
    from petrel_client.client import Client
ModuleNotFoundError: No module named 'petrel_client'
```

**Comment by Coach257** [comment]
Sorry for the mistake. This code is used for loading extra data from ceph, which is not included in LAMM itself. You can fix this by simply delete this code and the related code. These code does not affect the training and inference process.

**Comment by OpenLAMM** [comment]
This issue will be closed as seemed to be resolved. Please re-open if needed.
